name: Lint and tests

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: codecov/codecov-action@v1.0.5
      with:
       name: cloudis.dev
       token: "${{secrets.CODECOV_TOKEN}}"
       file: coverage/lcov.info
    - uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: '1.12.13+hotfix.6'
        channel: 'beta' # or: 'dev' or 'beta'

    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test --coverage    
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage/lcov.info #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        fail_ci_if_error: true #optional (default = false
    - run: flutter build web

