name: Firebase Deployement

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: '1.12.13+hotfix.6'
        channel: 'beta' # or: 'dev' or 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - run: |
        cp -r ./web/* ./build/web
        npm install -g firebase-tools
        firebase deploy --token "${{secrets.FIREBASE_TOKEN}}"

