name: Deploy to Firebase

on: 
  push:
    branches: 
    - master

jobs:
  lint-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Upgrade flutter
        run: |
          flutter channel beta
          flutter upgrade
      - name: Install packages
        run: |
          cd ./portfolio
          flutter pub get
      - name: Lint
        run: |
          cd ./portfolio
          flutter analyze
      - name: Unit test
        run: |
          cd ./portfolio
          flutter test
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Web app
      run: |
        cd ./portfolio
        flutter build web --release
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Firebase Hosting
      run: |
        cd ./portfolio
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
